// <auto-generated />
using System;
using DeliverPage.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DeliverPage.Migrations
{
    [DbContext(typeof(DeliveryDbContext))]
    partial class DeliveryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DeliverPage.Model.Delivery", b =>
                {
                    b.Property<int>("DeliveryId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BicycleId");

                    b.Property<string>("BicycleNumber");

                    b.Property<int>("BookingId");

                    b.Property<DateTime>("Cancelationtime");

                    b.Property<DateTime>("ConfirmationTime");

                    b.Property<DateTime>("DateTime");

                    b.Property<DateTime>("DeliverTime");

                    b.Property<string>("DeliveryAddress");

                    b.Property<string>("DeliveryUserName");

                    b.Property<double>("Deliverylat");

                    b.Property<double>("Deliverylng");

                    b.Property<DateTime>("OrderTime");

                    b.Property<string>("Status");

                    b.Property<string>("UserName");

                    b.HasKey("DeliveryId");

                    b.ToTable("delivery");
                });
#pragma warning restore 612, 618
        }
    }
}
