// <auto-generated />
using MapPointApi.model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MapPointApi.Migrations
{
    [DbContext(typeof(HubDbContext))]
    [Migration("20191017052650_hubcreation")]
    partial class hubcreation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MapPointApi.model.Hub", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("country");

                    b.Property<double>("latitude");

                    b.Property<string>("locality");

                    b.Property<double>("longitude");

                    b.Property<int>("postal");

                    b.Property<string>("short_country");

                    b.Property<string>("short_locality");

                    b.Property<string>("short_sub_locality_l1");

                    b.Property<string>("short_sub_locality_l2");

                    b.Property<string>("sub_locality_l1");

                    b.Property<string>("sub_locality_l2");

                    b.HasKey("id");

                    b.ToTable("hubs");
                });
#pragma warning restore 612, 618
        }
    }
}
